### ISSUE TITLE
Error when running Criclive.py

### ISSUE THREAD

**Issue by ScrumpyJack** [datta07/Live-Cricket-Scores#4]
Looks like there is a problem with the web socket.
I'm getting the following error, but there is nothing more I can do here as the websocket code is not avaiable.

🦄 ❯ python3 Criclive.py
```
Traceback (most recent call last):
  File "/home/user/src/Live-Cricket-Scores/Criclive.py", line 119, in <module>
    liveProcess=CricLive('wss://criclive-72dee-43d33.firebaseio.com/.ws?ns=criclive-72dee-43d33&v=5')
  File "/home/user/src/Live-Cricket-Scores/Criclive.py", line 21, in __init__
    self.initialSetup() # Loading for initial setup
  File "/home/user/src/Live-Cricket-Scores/Criclive.py", line 42, in initialSetup
    if (data[i]['con']['mstus']=='L'):
KeyError: 'con'
```

**Comment by datta07** [comment]
Thanks for the issue, any how solved it.watch now😅
